alter session set "_ORACLE_SCRIPT"=true;

CREATE ROLE ADMIN_ROLE;

GRANT ALL ON USERS TO ADMIN_ROLE;
GRANT ALL ON PLAYES TO ADMIN_ROLE;
GRANT ALL ON TEAMS TO ADMIN_ROLE;
GRANT ALL ON TICKETS TO ADMIN_ROLE;

CREATE ROLE FAN_ROLE;

GRANT ALL ON PLAYES TO FAN_ROLE;
GRANT ALL ON TEAMS TO FAN_ROLE;
GRANT ALL ON TICKETS TO FAN_ROLE;

-- users

CREATE USER Dan IDENTIFIED BY dss9;
GRANT ADMIN_ROLE TO Dan;

CREATE USER Dima IDENTIFIED BY dss;
GRANT FAN_ROLE TO Dima;